// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDwrzj3kWQBgBl28mGv78yBh0c8sgkupv4',
//     appId: '1:530255142204:android:186d2073706cabd1985239',
//     messagingSenderId: '530255142204',
//     projectId: 'rapidit-cc2a8',
//     storageBucket: 'rapidit-cc2a8.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDjHwZ2gSdkdNIs2ycAh-MxXI4kdgIIxp0',
//     appId: '1:530255142204:ios:eaf7a9f68f1b65c4985239',
//     messagingSenderId: '530255142204',
//     projectId: 'rapidit-cc2a8',
//     storageBucket: 'rapidit-cc2a8.firebasestorage.app',
//     iosClientId: '530255142204-eu7957ivd5cn5h9hr7gjlesdih5sjrqi.apps.googleusercontent.com',
//     iosBundleId: 'com.mtai.rapidituser',
//   );
// }
// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAFNFS-0-uStE8b6p4I629qCxeAP4DzX4I',
//     appId: '1:518313283812:web:16280120964a2385d4dcf1',
//     messagingSenderId: '518313283812',
//     projectId: 'e-health1-psa71c',
//     authDomain: 'e-health1-psa71c.firebaseapp.com',
//     storageBucket: 'e-health1-psa71c.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAnMddjg0aiHzOnQ7mwrLPpzWoscesDsWY',
//     appId: '1:518313283812:android:5051eb65d38ee214d4dcf1',
//     messagingSenderId: '518313283812',
//     projectId: 'e-health1-psa71c',
//     storageBucket: 'e-health1-psa71c.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAoVZnO_Qsyoo0xPdZcjF_RY0qucT6ISVg',
//     appId: '1:518313283812:ios:6fd36ac6c0400426d4dcf1',
//     messagingSenderId: '518313283812',
//     projectId: 'e-health1-psa71c',
//     storageBucket: 'e-health1-psa71c.appspot.com',
//     androidClientId: '518313283812-iqs8gdr353ed7301eo83tid0ndj2og5n.apps.googleusercontent.com',
//     iosClientId: '518313283812-rgmkimcdcn7o11dd2ob1a3vifobk79cc.apps.googleusercontent.com',
//     iosBundleId: 'com.mtaii.hpulse',
//   );
//
// }
// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAFNFS-0-uStE8b6p4I629qCxeAP4DzX4I',
//     appId: '1:518313283812:web:16280120964a2385d4dcf1',
//     messagingSenderId: '518313283812',
//     projectId: 'e-health1-psa71c',
//     authDomain: 'e-health1-psa71c.firebaseapp.com',
//     storageBucket: 'e-health1-psa71c.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAnMddjg0aiHzOnQ7mwrLPpzWoscesDsWY',
//     appId: '1:518313283812:android:5051eb65d38ee214d4dcf1',
//     messagingSenderId: '518313283812',
//     projectId: 'e-health1-psa71c',
//     storageBucket: 'e-health1-psa71c.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAoVZnO_Qsyoo0xPdZcjF_RY0qucT6ISVg',
//     appId: '1:518313283812:ios:6fd36ac6c0400426d4dcf1',
//     messagingSenderId: '518313283812',
//     projectId: 'e-health1-psa71c',
//     storageBucket: 'e-health1-psa71c.appspot.com',
//     androidClientId: '518313283812-iqs8gdr353ed7301eo83tid0ndj2og5n.apps.googleusercontent.com',
//     iosClientId: '518313283812-rgmkimcdcn7o11dd2ob1a3vifobk79cc.apps.googleusercontent.com',
//     iosBundleId: 'com.mtaii.hpulse',
//   );
//
// }

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAS71Z3v74AjRoDYCwJ7dT8jyb8KBiOGqA",
      authDomain: "lawncare-workshop-aj990c.firebaseapp.com",
      projectId: "lawncare-workshop-aj990c",
      storageBucket: "lawncare-workshop-aj990c.firebasestorage.app",
      messagingSenderId: "128651160740",
      appId: "1:128651160740:web:261928d5308a9442874a31"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAS71Z3v74AjRoDYCwJ7dT8jyb8KBiOGqA",
      authDomain: "lawncare-workshop-aj990c.firebaseapp.com",
      projectId: "lawncare-workshop-aj990c",
      storageBucket: "lawncare-workshop-aj990c.firebasestorage.app",
      messagingSenderId: "128651160740",
      appId: "1:128651160740:android:0fbdcd817bb2b9f7874a31"
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyAS71Z3v74AjRoDYCwJ7dT8jyb8KBiOGqA",
      authDomain: "lawncare-workshop-aj990c.firebaseapp.com",
      projectId: "lawncare-workshop-aj990c",
      storageBucket: "lawncare-workshop-aj990c.firebasestorage.app",
      messagingSenderId: "128651160740",
      appId: "1:128651160740:ios:0b12f72d5dec32ed874a31"
  );

}